from app.exceptions.database.DatabaseException import DatabaseException


class UsuarioEntityException(DatabaseException):
    ...
